inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb
    - spec/dummy/db/schema.rb
    - html_gen.gemspec
  NewCops: enable
  TargetRubyVersion: 2.7.8

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# Metrics/AbcSize:
#   Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

# Metrics/CyclomaticComplexity:
#   Max: 10

# Metrics/MethodLength:
#   Max: 50

# Metrics/PerceivedComplexity:
#   Max: 10

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Will report offences for many places that are much more readable without using a guard clause
Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true

Style/WordArray:
  Enabled: false
