# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: html_gen 0.0.16 ruby lib

Gem::Specification.new do |s|
  s.name = "html_gen".freeze
  s.version = "0.0.16"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kasper Johansen".freeze]
  s.date = "2017-07-13"
  s.description = "A small framework for generating HTML.".freeze
  s.email = "k@spernj.org".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".rubocop_todo.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "html_gen.gemspec",
    "lib/html_gen.rb",
    "lib/html_gen/element.rb",
    "lib/html_gen/parser.rb",
    "lib/html_gen/text_ele.rb",
    "shippable.yml",
    "spec/html_gen/element_spec.rb",
    "spec/html_gen_parser_spec.rb",
    "spec/html_gen_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/html_gen".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "A small framework for generating HTML.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<string-cases>.freeze, [">= 0"])
      s.add_development_dependency(%q<best_practice_project>.freeze, ["= 0.0.10"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["= 2.3.3"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>.freeze, ["= 3.5.0"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
    else
      s.add_dependency(%q<string-cases>.freeze, [">= 0"])
      s.add_dependency(%q<best_practice_project>.freeze, ["= 0.0.10"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>.freeze, ["= 2.3.3"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<rspec>.freeze, ["= 3.5.0"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<string-cases>.freeze, [">= 0"])
    s.add_dependency(%q<best_practice_project>.freeze, ["= 0.0.10"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, ["= 2.3.3"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<rspec>.freeze, ["= 3.5.0"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
  end
end

