# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: html_gen 0.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "html_gen"
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Johansen"]
  s.date = "2016-01-17"
  s.description = "A small framework for generating HTML."
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "html_gen.gemspec",
    "lib/html_gen.rb",
    "lib/html_gen/element.rb",
    "lib/html_gen/parser.rb",
    "lib/html_gen/text_ele.rb",
    "shippable.yml",
    "spec/html_gen_parser_spec.rb",
    "spec/html_gen_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/html_gen"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A small framework for generating HTML."

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new("1.2.0")
      s.add_runtime_dependency("string-cases", [">= 0"])
      s.add_development_dependency("rspec", ["~> 2.8.0"])
      s.add_development_dependency("rdoc", ["~> 3.12"])
      s.add_development_dependency("bundler", [">= 1.0.0"])
      s.add_development_dependency("jeweler", ["~> 1.8.4"])
    else
      s.add_dependency("string-cases", [">= 0"])
      s.add_dependency("rspec", ["~> 2.8.0"])
      s.add_dependency("rdoc", ["~> 3.12"])
      s.add_dependency("bundler", [">= 1.0.0"])
      s.add_dependency("jeweler", ["~> 1.8.4"])
    end
  else
    s.add_dependency("string-cases", [">= 0"])
    s.add_dependency("rspec", ["~> 2.8.0"])
    s.add_dependency("rdoc", ["~> 3.12"])
    s.add_dependency("bundler", [">= 1.0.0"])
    s.add_dependency("jeweler", ["~> 1.8.4"])
  end
end
